Практическое задание  
Обучите любую модель классификации на датасете IRIS до применения PCA и после него. Сравните качество классификации по отложенной выборке.  
Напишите свою реализацию метода главных компонент посредством сингулярного разложения с использованием функции numpy.linalg.svd().  

In [1]:
import numpy as np
from sklearn import metrics
from sklearn import datasets
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

import catboost as ctb

import seaborn as sns

In [2]:
# Загрузим игрушечный датасет из sklearn
iris = datasets.load_iris()
X = iris.data
X.shape

(150, 4)

In [3]:
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [4]:
X_test.shape

(45, 4)

In [5]:
model = ctb.CatBoostClassifier()
model.fit(X_train, y_train)
print(model)

Learning rate set to 0.070535
0:	learn: 1.0158560	total: 153ms	remaining: 2m 32s
1:	learn: 0.9559209	total: 156ms	remaining: 1m 17s
2:	learn: 0.9024653	total: 158ms	remaining: 52.5s
3:	learn: 0.8441637	total: 160ms	remaining: 40s
4:	learn: 0.7967177	total: 161ms	remaining: 32.1s
5:	learn: 0.7570304	total: 164ms	remaining: 27.1s
6:	learn: 0.7127928	total: 166ms	remaining: 23.5s
7:	learn: 0.6747743	total: 169ms	remaining: 21s
8:	learn: 0.6409302	total: 171ms	remaining: 18.8s
9:	learn: 0.6076929	total: 176ms	remaining: 17.4s
10:	learn: 0.5716956	total: 178ms	remaining: 16s
11:	learn: 0.5488025	total: 180ms	remaining: 14.8s
12:	learn: 0.5236103	total: 182ms	remaining: 13.8s
13:	learn: 0.4952281	total: 184ms	remaining: 12.9s
14:	learn: 0.4756991	total: 186ms	remaining: 12.2s
15:	learn: 0.4520682	total: 188ms	remaining: 11.5s
16:	learn: 0.4333506	total: 190ms	remaining: 11s
17:	learn: 0.4156313	total: 196ms	remaining: 10.7s
18:	learn: 0.4020110	total: 197ms	remaining: 10.2s
19:	learn: 0.3884

189:	learn: 0.0337184	total: 332ms	remaining: 1.42s
190:	learn: 0.0335091	total: 333ms	remaining: 1.41s
191:	learn: 0.0333253	total: 334ms	remaining: 1.41s
192:	learn: 0.0330986	total: 335ms	remaining: 1.4s
193:	learn: 0.0328920	total: 336ms	remaining: 1.39s
194:	learn: 0.0326815	total: 337ms	remaining: 1.39s
195:	learn: 0.0324573	total: 337ms	remaining: 1.38s
196:	learn: 0.0322184	total: 338ms	remaining: 1.38s
197:	learn: 0.0320083	total: 339ms	remaining: 1.37s
198:	learn: 0.0318127	total: 340ms	remaining: 1.37s
199:	learn: 0.0315862	total: 340ms	remaining: 1.36s
200:	learn: 0.0313820	total: 341ms	remaining: 1.35s
201:	learn: 0.0312058	total: 342ms	remaining: 1.35s
202:	learn: 0.0310090	total: 343ms	remaining: 1.34s
203:	learn: 0.0307881	total: 343ms	remaining: 1.34s
204:	learn: 0.0305984	total: 344ms	remaining: 1.33s
205:	learn: 0.0304215	total: 345ms	remaining: 1.33s
206:	learn: 0.0302217	total: 346ms	remaining: 1.32s
207:	learn: 0.0300118	total: 347ms	remaining: 1.32s
208:	learn: 0

389:	learn: 0.0139863	total: 492ms	remaining: 769ms
390:	learn: 0.0139500	total: 492ms	remaining: 767ms
391:	learn: 0.0138985	total: 493ms	remaining: 765ms
392:	learn: 0.0138564	total: 494ms	remaining: 763ms
393:	learn: 0.0137960	total: 495ms	remaining: 761ms
394:	learn: 0.0137480	total: 496ms	remaining: 759ms
395:	learn: 0.0137074	total: 496ms	remaining: 757ms
396:	learn: 0.0136757	total: 497ms	remaining: 755ms
397:	learn: 0.0136296	total: 498ms	remaining: 753ms
398:	learn: 0.0135929	total: 499ms	remaining: 751ms
399:	learn: 0.0135585	total: 500ms	remaining: 749ms
400:	learn: 0.0135135	total: 500ms	remaining: 747ms
401:	learn: 0.0134676	total: 501ms	remaining: 745ms
402:	learn: 0.0134260	total: 502ms	remaining: 744ms
403:	learn: 0.0133880	total: 503ms	remaining: 742ms
404:	learn: 0.0133456	total: 504ms	remaining: 740ms
405:	learn: 0.0132942	total: 504ms	remaining: 738ms
406:	learn: 0.0132622	total: 505ms	remaining: 736ms
407:	learn: 0.0132222	total: 506ms	remaining: 734ms
408:	learn: 

585:	learn: 0.0086996	total: 655ms	remaining: 463ms
586:	learn: 0.0086844	total: 656ms	remaining: 462ms
587:	learn: 0.0086645	total: 657ms	remaining: 461ms
588:	learn: 0.0086483	total: 658ms	remaining: 459ms
589:	learn: 0.0086285	total: 659ms	remaining: 458ms
590:	learn: 0.0086072	total: 660ms	remaining: 457ms
591:	learn: 0.0085924	total: 661ms	remaining: 456ms
592:	learn: 0.0085755	total: 662ms	remaining: 454ms
593:	learn: 0.0085587	total: 663ms	remaining: 453ms
594:	learn: 0.0085441	total: 663ms	remaining: 452ms
595:	learn: 0.0085291	total: 664ms	remaining: 450ms
596:	learn: 0.0085095	total: 665ms	remaining: 449ms
597:	learn: 0.0084877	total: 666ms	remaining: 448ms
598:	learn: 0.0084697	total: 667ms	remaining: 447ms
599:	learn: 0.0084541	total: 668ms	remaining: 445ms
600:	learn: 0.0084418	total: 669ms	remaining: 444ms
601:	learn: 0.0084261	total: 670ms	remaining: 443ms
602:	learn: 0.0084058	total: 671ms	remaining: 442ms
603:	learn: 0.0083946	total: 672ms	remaining: 440ms
604:	learn: 

783:	learn: 0.0062582	total: 819ms	remaining: 226ms
784:	learn: 0.0062490	total: 820ms	remaining: 225ms
785:	learn: 0.0062364	total: 821ms	remaining: 224ms
786:	learn: 0.0062283	total: 822ms	remaining: 222ms
787:	learn: 0.0062164	total: 823ms	remaining: 221ms
788:	learn: 0.0062086	total: 823ms	remaining: 220ms
789:	learn: 0.0062014	total: 824ms	remaining: 219ms
790:	learn: 0.0061925	total: 825ms	remaining: 218ms
791:	learn: 0.0061845	total: 826ms	remaining: 217ms
792:	learn: 0.0061758	total: 827ms	remaining: 216ms
793:	learn: 0.0061678	total: 827ms	remaining: 215ms
794:	learn: 0.0061582	total: 828ms	remaining: 214ms
795:	learn: 0.0061494	total: 829ms	remaining: 212ms
796:	learn: 0.0061394	total: 830ms	remaining: 211ms
797:	learn: 0.0061319	total: 831ms	remaining: 210ms
798:	learn: 0.0061207	total: 832ms	remaining: 209ms
799:	learn: 0.0061148	total: 832ms	remaining: 208ms
800:	learn: 0.0061060	total: 833ms	remaining: 207ms
801:	learn: 0.0060948	total: 834ms	remaining: 206ms
802:	learn: 

991:	learn: 0.0048494	total: 983ms	remaining: 7.92ms
992:	learn: 0.0048433	total: 983ms	remaining: 6.93ms
993:	learn: 0.0048380	total: 984ms	remaining: 5.94ms
994:	learn: 0.0048322	total: 985ms	remaining: 4.95ms
995:	learn: 0.0048266	total: 986ms	remaining: 3.96ms
996:	learn: 0.0048199	total: 987ms	remaining: 2.97ms
997:	learn: 0.0048160	total: 988ms	remaining: 1.98ms
998:	learn: 0.0048108	total: 988ms	remaining: 989us
999:	learn: 0.0048056	total: 989ms	remaining: 0us


In [6]:
expected_y  = y_test
predicted_y = model.predict(X_test)

In [7]:
print(metrics.classification_report(expected_y, predicted_y))
print(metrics.confusion_matrix(expected_y, predicted_y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.83      0.91        18
           2       0.83      1.00      0.91        15

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.94      0.93      0.93        45

[[12  0  0]
 [ 0 15  3]
 [ 0  0 15]]


PCA

In [8]:
from sklearn.decomposition import PCA
import pandas as pd

In [9]:
df = pd.DataFrame(data= X, columns = ['sepal length','sepal width','petal length','petal width'])

In [10]:
df.head()

sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [13]:
df_y = pd.DataFrame(y, columns = ['y'])

In [18]:
df_y.sample(5)

y
83   1
27   0
87   1
42   0
147  2

In [25]:
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train)

In [26]:
df_pca = pd.DataFrame(data = X_train_pca, columns = ['component_one', 'component_two'])

In [27]:
df_pca.head()

component_one  component_two
0       2.464194       0.482074
1       2.630030       0.084013
2       0.979917      -0.007575
3       1.263209      -0.119363
4       2.252007      -0.166438

In [28]:
df_r = pd.concat([df_pca, df_y[['y']]], axis = 1)

In [29]:
df_r.head()

component_one  component_two  y
0       2.464194       0.482074  0
1       2.630030       0.084013  0
2       0.979917      -0.007575  0
3       1.263209      -0.119363  0
4       2.252007      -0.166438  0

In [30]:
df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   component_one  105 non-null    float64
 1   component_two  105 non-null    float64
 2   y              150 non-null    int32  
dtypes: float64(2), int32(1)
memory usage: 3.1 KB


In [31]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(df_r[['component_one', 'component_two']], df_r[['y']], test_size=0.30)

In [32]:
X_train_pca.shape

(105, 2)

In [33]:
model_pca = ctb.CatBoostClassifier()
model_pca.fit(X_train_pca, y_train_pca)
print(model)

Learning rate set to 0.070535
0:	learn: 1.0475367	total: 1.78ms	remaining: 1.78s
1:	learn: 1.0085589	total: 3.5ms	remaining: 1.75s
2:	learn: 0.9665162	total: 5.33ms	remaining: 1.77s
3:	learn: 0.9299865	total: 7.14ms	remaining: 1.78s
4:	learn: 0.8970879	total: 8.83ms	remaining: 1.76s
5:	learn: 0.8668591	total: 10.6ms	remaining: 1.76s
6:	learn: 0.8375440	total: 12.5ms	remaining: 1.78s
7:	learn: 0.8130169	total: 14.4ms	remaining: 1.79s
8:	learn: 0.7900714	total: 16.2ms	remaining: 1.78s
9:	learn: 0.7696709	total: 18.1ms	remaining: 1.79s
10:	learn: 0.7512185	total: 20.1ms	remaining: 1.8s
11:	learn: 0.7323344	total: 22ms	remaining: 1.81s
12:	learn: 0.7177287	total: 23.8ms	remaining: 1.81s
13:	learn: 0.7018925	total: 25.7ms	remaining: 1.81s
14:	learn: 0.6870390	total: 27.7ms	remaining: 1.82s
15:	learn: 0.6747483	total: 29.5ms	remaining: 1.81s
16:	learn: 0.6621506	total: 31.4ms	remaining: 1.82s
17:	learn: 0.6494650	total: 32.5ms	remaining: 1.77s
18:	learn: 0.6379380	total: 34.4ms	remaining: 1.

222:	learn: 0.2026221	total: 485ms	remaining: 1.69s
223:	learn: 0.2020215	total: 488ms	remaining: 1.69s
224:	learn: 0.2014510	total: 491ms	remaining: 1.69s
225:	learn: 0.2008253	total: 494ms	remaining: 1.69s
226:	learn: 0.1999972	total: 496ms	remaining: 1.69s
227:	learn: 0.1989991	total: 499ms	remaining: 1.69s
228:	learn: 0.1986598	total: 501ms	remaining: 1.69s
229:	learn: 0.1981912	total: 503ms	remaining: 1.68s
230:	learn: 0.1974330	total: 506ms	remaining: 1.68s
231:	learn: 0.1968977	total: 509ms	remaining: 1.68s
232:	learn: 0.1962200	total: 511ms	remaining: 1.68s
233:	learn: 0.1956713	total: 514ms	remaining: 1.68s
234:	learn: 0.1951617	total: 516ms	remaining: 1.68s
235:	learn: 0.1946128	total: 519ms	remaining: 1.68s
236:	learn: 0.1941359	total: 522ms	remaining: 1.68s
237:	learn: 0.1931346	total: 525ms	remaining: 1.68s
238:	learn: 0.1923151	total: 527ms	remaining: 1.68s
239:	learn: 0.1916569	total: 529ms	remaining: 1.67s
240:	learn: 0.1911190	total: 531ms	remaining: 1.67s
241:	learn: 

383:	learn: 0.1232642	total: 824ms	remaining: 1.32s
384:	learn: 0.1229467	total: 826ms	remaining: 1.32s
385:	learn: 0.1226744	total: 828ms	remaining: 1.32s
386:	learn: 0.1222911	total: 830ms	remaining: 1.31s
387:	learn: 0.1219109	total: 833ms	remaining: 1.31s
388:	learn: 0.1214998	total: 835ms	remaining: 1.31s
389:	learn: 0.1212662	total: 837ms	remaining: 1.31s
390:	learn: 0.1209230	total: 839ms	remaining: 1.31s
391:	learn: 0.1205564	total: 841ms	remaining: 1.3s
392:	learn: 0.1201614	total: 843ms	remaining: 1.3s
393:	learn: 0.1199928	total: 845ms	remaining: 1.3s
394:	learn: 0.1198377	total: 847ms	remaining: 1.3s
395:	learn: 0.1196549	total: 849ms	remaining: 1.29s
396:	learn: 0.1193867	total: 852ms	remaining: 1.29s
397:	learn: 0.1190022	total: 854ms	remaining: 1.29s
398:	learn: 0.1187185	total: 856ms	remaining: 1.29s
399:	learn: 0.1182827	total: 858ms	remaining: 1.29s
400:	learn: 0.1178896	total: 860ms	remaining: 1.28s
401:	learn: 0.1174393	total: 861ms	remaining: 1.28s
402:	learn: 0.11

544:	learn: 0.0847199	total: 1.16s	remaining: 968ms
545:	learn: 0.0844823	total: 1.16s	remaining: 966ms
546:	learn: 0.0843124	total: 1.16s	remaining: 964ms
547:	learn: 0.0841882	total: 1.17s	remaining: 962ms
548:	learn: 0.0840302	total: 1.17s	remaining: 959ms
549:	learn: 0.0838145	total: 1.17s	remaining: 957ms
550:	learn: 0.0835286	total: 1.17s	remaining: 955ms
551:	learn: 0.0831867	total: 1.17s	remaining: 953ms
552:	learn: 0.0829574	total: 1.18s	remaining: 950ms
553:	learn: 0.0827701	total: 1.18s	remaining: 948ms
554:	learn: 0.0826162	total: 1.18s	remaining: 946ms
555:	learn: 0.0824192	total: 1.18s	remaining: 944ms
556:	learn: 0.0822417	total: 1.18s	remaining: 941ms
557:	learn: 0.0820680	total: 1.19s	remaining: 939ms
558:	learn: 0.0819475	total: 1.19s	remaining: 937ms
559:	learn: 0.0817658	total: 1.19s	remaining: 935ms
560:	learn: 0.0815702	total: 1.19s	remaining: 933ms
561:	learn: 0.0813578	total: 1.19s	remaining: 931ms
562:	learn: 0.0811711	total: 1.2s	remaining: 929ms
563:	learn: 0

706:	learn: 0.0620337	total: 1.5s	remaining: 620ms
707:	learn: 0.0619745	total: 1.5s	remaining: 618ms
708:	learn: 0.0618688	total: 1.5s	remaining: 616ms
709:	learn: 0.0617714	total: 1.5s	remaining: 614ms
710:	learn: 0.0617169	total: 1.5s	remaining: 611ms
711:	learn: 0.0616145	total: 1.51s	remaining: 609ms
712:	learn: 0.0614869	total: 1.51s	remaining: 608ms
713:	learn: 0.0613977	total: 1.51s	remaining: 606ms
714:	learn: 0.0613210	total: 1.51s	remaining: 604ms
715:	learn: 0.0612085	total: 1.52s	remaining: 602ms
716:	learn: 0.0610864	total: 1.52s	remaining: 600ms
717:	learn: 0.0609937	total: 1.52s	remaining: 598ms
718:	learn: 0.0609328	total: 1.52s	remaining: 596ms
719:	learn: 0.0608598	total: 1.53s	remaining: 594ms
720:	learn: 0.0607272	total: 1.53s	remaining: 592ms
721:	learn: 0.0606231	total: 1.53s	remaining: 590ms
722:	learn: 0.0605564	total: 1.53s	remaining: 588ms
723:	learn: 0.0604956	total: 1.54s	remaining: 586ms
724:	learn: 0.0604235	total: 1.54s	remaining: 584ms
725:	learn: 0.060

870:	learn: 0.0483056	total: 1.83s	remaining: 272ms
871:	learn: 0.0482493	total: 1.84s	remaining: 270ms
872:	learn: 0.0481859	total: 1.84s	remaining: 268ms
873:	learn: 0.0481376	total: 1.84s	remaining: 266ms
874:	learn: 0.0480753	total: 1.84s	remaining: 264ms
875:	learn: 0.0480066	total: 1.85s	remaining: 262ms
876:	learn: 0.0479433	total: 1.85s	remaining: 259ms
877:	learn: 0.0479018	total: 1.85s	remaining: 257ms
878:	learn: 0.0478214	total: 1.85s	remaining: 255ms
879:	learn: 0.0477405	total: 1.86s	remaining: 253ms
880:	learn: 0.0476717	total: 1.86s	remaining: 251ms
881:	learn: 0.0475953	total: 1.86s	remaining: 249ms
882:	learn: 0.0475234	total: 1.86s	remaining: 247ms
883:	learn: 0.0474720	total: 1.86s	remaining: 245ms
884:	learn: 0.0474099	total: 1.87s	remaining: 243ms
885:	learn: 0.0473587	total: 1.87s	remaining: 240ms
886:	learn: 0.0472980	total: 1.87s	remaining: 238ms
887:	learn: 0.0471945	total: 1.87s	remaining: 236ms
888:	learn: 0.0471436	total: 1.87s	remaining: 234ms
889:	learn: 

In [34]:
expected_y_pca  = y_test_pca
predicted_y_pca = model_pca.predict(X_test_pca)

In [35]:
print(metrics.classification_report(expected_y_pca, predicted_y_pca))
print(metrics.confusion_matrix(expected_y_pca, predicted_y_pca))

              precision    recall  f1-score   support

           0       0.43      0.32      0.36        19
           1       0.39      0.60      0.47        15
           2       1.00      0.73      0.84        11

    accuracy                           0.51        45
   macro avg       0.61      0.55      0.56        45
weighted avg       0.56      0.51      0.52        45

[[ 6 13  0]
 [ 6  9  0]
 [ 2  1  8]]


In [36]:
print(metrics.classification_report(expected_y, predicted_y))
print(metrics.confusion_matrix(expected_y, predicted_y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.83      0.91        18
           2       0.83      1.00      0.91        15

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.94      0.93      0.93        45

[[12  0  0]
 [ 0 15  3]
 [ 0  0 15]]


C PCA явно качество стало хуже, но этот датасет не нуждается в понижении размерности

## numpy.linalg.svd()

In [68]:
X = np.random.normal(size=[150,4])

In [69]:
df = pd.DataFrame(X)

In [70]:
df.head()

0         1         2         3
0 -0.396983 -1.156423  0.248381 -1.310929
1 -0.765302  0.020662  0.238294 -2.446115
2 -0.274813 -0.706302  0.360957  0.202848
3 -1.332770 -1.154290  0.287957 -0.181508
4 -1.667763 -0.504344 -1.199451  0.166317

In [71]:
P, D, Q = np.linalg.svd(df, full_matrices=False)

In [72]:
df_P = pd.DataFrame(P)

In [73]:
# X_a = np.matmul(np.matmul(P, np.diag(D)), Q)

X_a = P @ np.diag(D) @ Q

In [74]:
print(np.std(X), np.std(X_a), np.std(X - X_a))

0.993145275718599 0.9931452757185996 6.951341192625555e-16
